remote_theme: pmarsceill/just-the-docs

color_scheme: dark

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false

relative_links:
  enabled:     true
  collections: false

readme_index:
  enabled:          false
  remove_originals: false
  with_frontmatter: false

plugins:
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-readme-index
